# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - hadley/pkgdown

r:
- 3.1
- 3.2
- oldrel
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    r: release
  local_dir: docs
