# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - r-lib/pkgdown

r:
- 3.1
- 3.2
- oldrel
- release
- devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

before_deploy:
  - Rscript -e 'devtools::install_github("nbenn/s3vec"); pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $TRAVIS_R_VERSION_STRING = release
  local_dir: docs
